/def -i -F -q -t"a big mummy is bashing around with his sword (undead)" dester1 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"a gray beholder is floating here (evil)" dester2 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"a green beholder is floating here (nasty)" dester3 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Warl Su, the jailed samurai" dester4 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Edward Amberley, the family priest" dester5 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Grandmother Elizabeth Amberley" dester6 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Gilljam, elite soldier and universal beauty" dester7 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Aviel, commander of the imperial elite forces" dester8 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Erik Fzurrp-Fjongabolos, the Auctioneer" dester9 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Doc the Bank Robber" dester10 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Greedy the Bank Robber" dester11 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Lefty the Bank Robber" dester12 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Netrunner the Bank Robber" dester13 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Righty the Bank Robber" dester14 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Sleazy the Bank Robber" dester15 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Smelly the Bank Robber" dester16 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Sneezy the Bank Robber" dester17 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Sarah Greenpond the old widow" dester18 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Walith Kediralath, trying to hide in the shadows" dester19 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"an infernal knight vowed to guard the vault (undead)" dester20 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"a dark shade of a corrupted paladin (undead)" dester21 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"a pile of gold coins nudges closer" dester22 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Elven chef preparing dinner" dester23 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Rudolf the smith" dester24 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Petrus the very quiet Donaru librarian" dester25 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"This is the hillgiant's wife,she is drawing water from the well" dester26 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"There is a very old man with shiny white oozing eyes" dester27 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"The queen is pacing around, looking for something to do" dester28 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"a torturer demon of the unspoken one" dester29 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Dark Knight is grinning here" dester30 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Odo, the brave hunter" dester31 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Kizarwexius the moondragon sways above you, smoke rising from her nostrils and acid dripping from her fangs" dester32 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Dag Dag Schwingenator, ruler of Magerathia" dester33 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Melcross, the deadly demon leader" dester34 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Zeltjin the head warlock of Tiamat" dester35 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Pelitar the old retired village wizard" dester36 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Julius, the king of the castle" dester37 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"(smoke demon)" dester38 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Molly, Despana's little bundle of joy" dester39 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Pedro, Despana's pride and joy" dester40 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Icalia, the ice demon" dester41 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Alena, the acquisitionist" dester42 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"A small impish demon" dester43 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Ditianna, the bride of Tomtor" dester44 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
;/def -i -F -q -t"Reddist the lord of Reavers" dester45 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"The Master Sorcerer of the Temple of Sarku is meditating here." dester46 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"the wight of Dentirion (evil) (undead)" dester47 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"a spherical floating beast with one gigantic eye is gazing at you" dester48 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"an ethereal being is silently hovering in the air" dester49 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"the captain of a ship" dester50 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"The High Priestess of the temple" dester51 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Elemental prince of water" dester52 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"An urvile loremaster is preparing to crush the resistance" dester53 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"Elder Petron has rallied some defenders" dester54 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"a nasty looking witch" dester55 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"The boatman of the River Styx" dester56 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"A Gray Slaad-Lord is hopping around here (undead)" dester57 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"A HUGE lizardman torturer is here, attacking YOU!" dester58 = /substitute -p %* @{BCbgred,Cwhite}[DESTS]@{n}
/def -i -F -q -t"A man wearing a white coat sits behind a desk" dester59 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"A middle-aged nurse stands here waiting for you" dester60 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"A young, fresh out of school medic stands here" dester61 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"A old comfortable looking woman is looking at you" dester62 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"A old lecherous doctor, reminds you of someone from old Vienna" dester63 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Lacramobo the rentkeeper leans against a desk looking bored" dester64 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Morden the Shadowman" dester65 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Galigord the slightly overweight rentkeeper is on his break" dester66 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"The Master of the Arena, a humanoid giving off a black aura" dester67 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"The Demilich Ogaitnas Iuqnarf" dester68 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"An ancient lich stares at you with hatred (undead)" dester69 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Krystanimyth, the Dreaded Dracolich, the Ever Dragon" dester70 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"a torturer demon of the unspoken one" dester71 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"the supreme urvile loremaster rests in his cave" dester72 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Bzatah, the psionlich (undead)" dester73 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Thulanic, the gatelich (undead)" dester74 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Uruthmatium, the darklich (undead)" dester75 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Threumathuran, the deathlich (undead)" dester76 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Inturnastabxlien, the ancient and powerful demi-lich (undead)" dester77 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"An old-looking hermit" dester78 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"The high Lord Despana" dester79 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Gotryt the mighty lich king stands here (undead)" dester80 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Zifnab's Gigantic Dragon" dester81 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Chesire the rentkeeper is purring silently here" dester82 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"The Beholder, the Warden, 'Grrzzaaah' of Prison complex" dester83 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"A large sperical beholder hovers here" dester84 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"Killusia, the mistress of pain and misery" dester85 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"A handsome ghostly humanoid is hovering over here (undead)" dester86 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"A beautiful ghostly humanoid hovers over here. (undead)" dester87 = /substitute -p %* @{BCbgred,Cwhite}[DISINTEGRATE]@{n}
/def -i -F -q -t"The Zhentorian Captain is planning here" dester88 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"a shy leopard-furred catfolk walks by very slowly" dester89 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"A robed drow is standing here calmly." dester90 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"Ceche the neuter Gatekeeper of the mansion" dester91 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"an orc in ceremonial garb stands here" dester92 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"Puff of fiery smoke" dester93 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"A Cloak Enshrouded Figure Blocks the Stairway" dester94 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"A short grinning red demon of Twilight" dester95 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"Skeleton guard clad in heavy armour" dester96 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"A pitfiend grinning wickedly at your misery" dester97 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"A pitfiend-king is lolling and wobbling raunchily here at your misery" dester98 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"fire elemental" dester99 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"The Lizardman Captain is here, attacking YOU" dester100 = /substitute -p %* @{BCbgred,Cwhite}[IMMOLATE]@{n}
/def -i -F -q -t"Axidia, Master of undeads" dester101 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
/def -i -F -q -t"A minion of Axidia tries to steal your soul (undead)" dester102 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
/def -i -F -q -t"a dark figure of a knight enveloped by darkness (undead)" dester103 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
/def -i -F -q -t"Alena, the acquisitionist" dester104 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
/def -i -F -q -t"a kobold rogue, lurking in shadows" dester105 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
/def -i -F -q -t"A short grinning black demon of Twilight" dester106 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
/def -i -F -q -t"a small elven child playing around" dester107 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
/def -i -F -q -t"A small orc is hiding in the shadows, trying to steal something" dester108 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
/def -i -F -q -t"a guardian spirit" dester109 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
/def -i -F -q -t"A meanie guenon digging the bones" dester110 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
/def -i -F -q -t"Liezeb the druid" dester111 = /substitute -p %* @{BCbgred,Cwhite}[ACQUISITION]@{n}
