/def -i -F -q -t'*\'Stand confused with lack of comprehension, pagan of mine for I know of the true belief, while death calls you, compel your soul to the true belief, for I offer you this redemption in the harmony of my true belief\.\.\'*' words_Achromatic_eyes = /substitute -p %* @{Cyellow}[Achromatic eyes]@{n}
/def -i -F -q -t'*\'fzz zur semen\'*' words_Acid_arrow = /substitute -p %* @{Cyellow}[Acid arrow]@{n} (acid3)
/def -i -F -q -t'*\'fzz mar nak grttzt\'*' words_Acid_blast = /substitute -p %* @{Cyellow}[Acid blast]@{n} (acid5)
/def -i -F -q -t'*\'fzz zur sanc gnatlnamauch\'*' words_Acid_rain = /substitute -p %* @{Cyellow}[Acid rain]@{n} (acid-A1)
/def -i -F -q -t'*\'fzz mar nak semen\'*' words_Acid_ray = /substitute -p %* @{Cyellow}[Acid ray]@{n} (acid4)
/def -i -F -q -t'*\'hfizz hfizz nglurglptz\'*' words_Acid_shield = /substitute -p %* @{Cyellow}[Acid shield]@{n} (acid-P2)
/def -i -F -q -t'*\'fzz mar nak grttzt gnatlnamauch\'*' words_Acid_storm = /substitute -p %* @{Cyellow}[Acid storm]@{n} (acid-A2)
/def -i -F -q -t'*\'fzz zur sanc\'*' words_Acid_wind = /substitute -p %* @{Cyellow}[Acid wind]@{n} (acid2)
/def -i -F -q -axBCbgred,Cwhite -t'*\'mesmr pulrl metism\'*' words_Acquisition = /substitute -p %* @{Cyellow}[Acquisition]@{n}
/def -i -F -q -t'*\'condiiit riimaynii\'*' words_Aegis = /substitute -p %* @{Cyellow}[Aegis]@{n}
/def -i -F -q -t'*\'xeddex mof\'*' words_Agility_accelerator = /substitute -p %* @{Cyellow}[Agility accelerator]@{n}
/def -i -F -q -t'*\'whooz\'*' words_Airsteel = /substitute -p %* @{Cyellow}[Airsteel]@{n}
/def -i -F -q -t'*\'tamakan natelo assim\'*' words_All-seeing_eye = /substitute -p %* @{Cyellow}[All-seeing eye]@{n}
/def -i -F -q -t'*\'siwwis uurthg\'*' words_Amnesia = /substitute -p %* @{Cyellow}[Amnesia]@{n}
/def -i -F -q -t'*\'yugzhrr paf\'*' words_Aneurysm = /substitute -p %* @{Cyellow}[Aneurysm]@{n}
/def -i -F -q -t'*\'Give my creation life\!\!\'*' words_Animate_golem = /substitute -p %* @{Cyellow}[Animate golem]@{n}
/def -i -F -q -t'*\'taikoja ma inhoan\'*' words_Anti_magic_field = /substitute -p %* @{Cyellow}[Anti magic field]@{n}
/def -i -F -q -t'*\'In the Shadows cast down by the moon, a certain Elven lord he strolls among the common folk, cloaked and hidden from recognition\. The dark streets of the Keep of Shadows, vehement Inns, dancing women appeasing patrons\.\. A vigorous gleam in his eye, a nod of knowledge and satisfaction; dreams slowly fulfilled as the notes of time pass, participating and watching the twists of life, Lord Shadowstring, the artful archwizard, grant us a fragment of chance\.\'*' words_Arches_favour = /substitute -p %* @{Cyellow}[Arches favour]@{n}
/def -i -F -q -t'*\'vaka tosi vanha vainamoinen\'*' words_Area_entropy = /substitute -p %* @{Cyellow}[Area entropy]@{n}
/def -i -F -q -t'*\'fooharribah inaminos cantor\'*' words_Armour_of_aether = /substitute -p %* @{Cyellow}[Armour of aether]@{n}
/def -i -F -q -t'*\'nitin mof\'*' words_Artificial_intelligence = /substitute -p %* @{Cyellow}[Artificial intelligence]@{n}
/def -i -F -q -t'*\'fooohh haaahhh booooloooooh\'*' words_Aura_detection = /substitute -p %* @{Cyellow}[Aura detection]@{n}
/def -i -F -q -t'*\'Feel your anger and strike with all your hatred\. Use your aggressive feelings and let the hate flow through you\.\'*' words_Aura_of_hate = /substitute -p %* @{Cyellow}[Aura of hate]@{n}
/def -i -F -q -t'*\'noccon mof\'*' words_Aura_of_power = /substitute -p %* @{Cyellow}[Aura of power]@{n}
/def -i -F -q -t'*\'englobo globo mc\'pop\'*' words_Aura_of_wind = /substitute -p %* @{Cyellow}[Aura of wind]@{n} (asphyx-P2)
/def -i -F -q -t'*\'siwwis mof\'*' words_Awareness = /substitute -p %* @{Cyellow}[Awareness]@{n}
/def -i -F -q -t'*\'havia kauhistus pois\'*' words_Banish = /substitute -p %* @{Cyellow}[Banish]@{n}
/def -i -F -q -t'*\'Satan down\'*' words_Banish_demons = /substitute -p %* @{Cyellow}[Banish demons]@{n}
/def -i -F -q -t'*\'Bastage\'*' words_Bastardly_balm = /substitute -p %* @{Cyellow}[Bastardly balm]@{n}
/def -i -F -q -t'*\'murraugh\'*' words_Bearskin = /substitute -p %* @{Cyellow}[Bearskin]@{n}
/def -i -F -q -t'*\'Azzarakk, take this sacrifice I offer thee\'*' words_Black_hole = /substitute -p %* @{Cyellow}[Black hole]@{n}
/def -i -F -q -t'*\'dsaflk aslfoir\'*' words_Blade_of_fire = /substitute -p %* @{Cyellow}[Blade of fire]@{n}
/def -i -F -q -t'*\'zot zur semen\'*' words_Blast_lightning = /substitute -p %* @{Cyellow}[Blast lightning]@{n} (elec3)
/def -i -F -q -t'*\'ghht mar nak grttzt\'*' words_Blast_vacuum = /substitute -p %* @{Cyellow}[Blast vacuum]@{n} (asphyx5)
/def -i -F -q -t'*\'Faerwon, grant your favor\!\'*' words_Bless_armament = /substitute -p %* @{Cyellow}[Bless armament]@{n}
/def -i -F -q -t'*\'\! \(\*\) \!\'*' words_Blessed_warmth = /substitute -p %* @{Cyellow}[Blessed warmth]@{n}
/def -i -F -q -t'*\'Benedic, Faerwon, nos et haec tua dona quae de tua largitate sumus sumpturi\'*' words_Blessing_of_faerwon = /substitute -p %* @{Cyellow}[Blessing of faerwon]@{n}
/def -i -F -q -t'*\'nilaehz arzocupne\'*' words_Blessing_of_tarmalen = /substitute -p %* @{Cyellow}[Blessing of tarmalen]@{n}
/def -i -F -q -t'*\'The sharper, the sweeter\'*' words_Blood_seeker = /substitute -p %* @{Cyellow}[Blood seeker]@{n}
/def -i -F -q -t'*\'ziiiuuuuns wiz\'*' words_Blurred_image = /substitute -p %* @{Cyellow}[Blurred image]@{n}
/def -i -F -q -t'*\'habbi urblk\'*' words_Call_pigeon = /substitute -p %* @{Cyellow}[Call pigeon]@{n}
/def -i -F -q -t'*\'It is time for the harvest of bone and blood\'*' words_Call_scythe = /substitute -p %* @{Cyellow}[Call scythe]@{n}
/def -i -F -q -t'*\'What child is this, who laid to rest on Mary\'s lap is sleeping, angels greet with anthems sweet while shepherds guard are keeping\? This, this is Christ the king, whom shephers guard and angels sing\. Haste, haste to bring him laude the babe, the son of Mary\!\'*' words_Campfire_tune = /substitute -p %* @{Cyellow}[Campfire tune]@{n}
/def -i -F -q -t'*\'eyem en da munnee\'*' words_Cash_flow = /substitute -p %* @{Cyellow}[Cash flow]@{n}
/def -i -F -q -t'*\'Shooting Star\'*' words_Catchy_singalong = /substitute -p %* @{Cyellow}[Catchy singalong]@{n}
/def -i -F -q -t'*\'rhuuuumm angotz klekltz\'*' words_Cause_critical_wounds = /substitute -p %* @{Cyellow}[Cause critical wounds]@{n}
/def -i -F -q -t'*\'tosi pieni neula\'*' words_Cause_light_wounds = /substitute -p %* @{Cyellow}[Cause light wounds]@{n}
/def -i -F -q -t'*\'rhuuuumm angotz amprltz\'*' words_Cause_serious_wounds = /substitute -p %* @{Cyellow}[Cause serious wounds]@{n}
/def -i -F -q -t'*\'zeriqum\'*' words_Celestial_haven = /substitute -p %* @{Cyellow}[Celestial haven]@{n}
/def -i -F -q -t'*\'zot zur semen gnatlnamauch\'*' words_Chain_lightning = /substitute -p %* @{Cyellow}[Chain lightning]@{n} (elec-A1)
/def -i -F -q -t'*\'shar ryo den\.\.\.Haa\!\'*' words_Channelball = /substitute -p %* @{Cyellow}[Channelball]@{n}
/def -i -F -q -t'*\'tsaibaa\'*' words_Channelbolt = /substitute -p %* @{Cyellow}[Channelbolt]@{n}
/def -i -F -q -t'*\'grhagrhagrhagrah gra gra Hyaa\!\'*' words_Channelburn = /substitute -p %* @{Cyellow}[Channelburn]@{n}
/def -i -F -q -t'*\'lecaps meeb nonnock\'*' words_Channelray = /substitute -p %* @{Cyellow}[Channelray]@{n}
/def -i -F -q -t'*\'grinurb sdan imflagrum\'*' words_Channelspray = /substitute -p %* @{Cyellow}[Channelspray]@{n}
/def -i -F -q -t'*\'ghht zur semen\'*' words_Chaos_bolt = /substitute -p %* @{Cyellow}[Chaos bolt]@{n} (asphyx3)
/def -i -F -q -t'*\'weaapytama wezup boomie\'*' words_Chaotic_warp = /substitute -p %* @{Cyellow}[Chaotic warp]@{n}
/def -i -F -q -t'*\'\# \!\(\'*' words_Charge_staff = /substitute -p %* @{Cyellow}[Charge staff]@{n}
/def -i -F -q -t'*\'cah zur fehh\'*' words_Chill_touch = /substitute -p %* @{Cyellow}[Chill touch]@{n} (cold1)
/def -i -F -q -t'*\'aalltyyuii regonza zirii\'*' words_Clairvoyance = /substitute -p %* @{Cyellow}[Clairvoyance]@{n}
/def -i -F -q -t'*\'To all the eyes around me, I wish to remain hidden, must I be seen when so far I have namelessly ridden\. To all those who relentlessly me seek or hound, covet I nothing but mayhaps a trifling wound\.\'*' words_Clandestine_thoughts = /substitute -p %* @{Cyellow}[Clandestine thoughts]@{n}
/def -i -F -q -t'*\'Ala itkeä iletys, parkua paha kuvatus\'*' words_Cleanse_heathen = /substitute -p %* @{Cyellow}[Cleanse heathen]@{n}
/def -i -F -q -t'*\'cah mar nak grttzt\'*' words_Cold_ray = /substitute -p %* @{Cyellow}[Cold ray]@{n} (cold5)
/def -i -F -q -t'*\'AeaH\*h\*\*\*Gdg\'*' words_Con_fioco = /substitute -p %* @{Cyellow}[Con fioco]@{n}
/def -i -F -q -t'*\'cah zur semen gnatlnamauch\'*' words_Cone_of_cold = /substitute -p %* @{Cyellow}[Cone of cold]@{n} (cold-A1)
/def -i -F -q -t'*\'sulphiraidzik hydrochloodriz gidz zuf\'*' words_Corrosion_shield = /substitute -p %* @{Cyellow}[Corrosion shield]@{n} (acid-P1)
/def -i -F -q -t'*\'ilma on sakeampaa kuin veri\'*' words_Create_air_armour = /substitute -p %* @{Cyellow}[Create air armour]@{n}
/def -i -F -q -t'*\'juustoa ja pullaa, sita mun maha halajaa\'*' words_Create_food = /substitute -p %* @{Cyellow}[Create food]@{n}
/def -i -F -q -t'*\'greeeenie fiiingerie\'*' words_Create_herb = /substitute -p %* @{Cyellow}[Create herb]@{n}
/def -i -F -q -t'*\'roope ankka rulettaa\'*' words_Create_money = /substitute -p %* @{Cyellow}[Create money]@{n}
/def -i -F -q -t'*\'\# \!\#\'*' words_Create_mud = /substitute -p %* @{Cyellow}[Create mud]@{n}
/def -i -F -q -t'*\'eki eki eki equifaxeki\'*' words_Credit_check = /substitute -p %* @{Cyellow}[Credit check]@{n}
/def -i -F -q -t'*\'judicandus mangenic\'*' words_Cure_critical_wounds = /substitute -p %* @{Cyellow}[Cure critical wounds]@{n}
/def -i -F -q -t'*\'judicandus mercuree\'*' words_Cure_light_wounds = /substitute -p %* @{Cyellow}[Cure light wounds]@{n}
/def -i -F -q -t'*\'freudemas egoid\'*' words_Cure_player = /substitute -p %* @{Cyellow}[Cure player]@{n}
/def -i -F -q -t'*\'judicandus ignius\'*' words_Cure_serious_wounds = /substitute -p %* @{Cyellow}[Cure serious wounds]@{n}
/def -i -F -q -t'*\'oli isa-sammakko, aiti-sammakko ja PIKKU-SAMMAKKO\!\!\'*' words_Curse = /substitute -p %* @{Cyellow}[Curse]@{n}
/def -i -F -q -t'*\'rtsstr uurthg\'*' words_Curse_of_ogre = /substitute -p %* @{Cyellow}[Curse of ogre]@{n}
/def -i -F -q -t'*\'nilaehz temnahecne neg\'*' words_Curse_of_tarmalen = /substitute -p %* @{Cyellow}[Curse of tarmalen]@{n}
/def -i -F -q -t'*\'Gawd DAMN IT\!\'*' words_Damn_armament = /substitute -p %* @{Cyellow}[Damn armament]@{n}
/def -i -F -q -t'*\'Dance my little blades, whip my enemies for I am the true fiend\. Dance, for I am the source that tweaks the winds\! Dance my blades, ravage at my command, for thou shall find sheaths in the abdomens of my foes\!\'*' words_Dancing_blades = /substitute -p %* @{Cyellow}[Dancing blades]@{n}
/def -i -F -q -t'*\'cah zur semen\'*' words_Darkfire = /substitute -p %* @{Cyellow}[Darkfire]@{n} (cold3)
/def -i -F -q -t'*\'na ful\'*' words_Darkness = /substitute -p %* @{Cyellow}[Darkness]@{n}
/def -i -F -q -t'*\'mumbo jumbo\'*' words_Deaths_door = /substitute -p %* @{Cyellow}[Deaths door]@{n}
/def -i -F -q -t'*\'kewa dan dol rae hout\'*' words_Degenerate_person = /substitute -p %* @{Cyellow}[Degenerate person]@{n}
/def -i -F -q -axBCbgred,Cwhite -t'*\'se on sarki nyt\'*' words_Destroy_armour = /substitute -p %* @{Cyellow}[Destroy armour]@{n}
/def -i -F -q -axBCbgred,Cwhite -t'*\'rikki ja poikki\'*' words_Destroy_weapon = /substitute -p %* @{Cyellow}[Destroy weapon]@{n}
/def -i -F -q -t'*\'annihilar hzzz golum\'*' words_Detect_alignment = /substitute -p %* @{Cyellow}[Detect alignment]@{n}
/def -i -F -q -t'*\'\$ \!\^\'*' words_Detect_poison = /substitute -p %* @{Cyellow}[Detect poison]@{n}
/def -i -F -q -t'*\'taxonimus zoologica whaddahellizzat\'*' words_Detect_race = /substitute -p %* @{Cyellow}[Detect race]@{n}
/def -i -F -q -t'*\'grrreee allblakkee\'*' words_Dim = /substitute -p %* @{Cyellow}[Dim]@{n}
/def -i -F -q -t'*\'prtolala offf pwerrrr\'*' words_Dimension_door = /substitute -p %* @{Cyellow}[Dimension door]@{n}
/def -i -F -q -t'*\'noccon uurthg\'*' words_Disease = /substitute -p %* @{Cyellow}[Disease]@{n}
/def -i -F -q -axBCbgred,Cwhite -t'*\'sahanpurua, shampanjaa ja vaahtokarkkeja\'*' words_Disintegrate = /substitute -p %* @{Cyellow}[Disintegrate]@{n}
/def -i -F -q -t'*\'Ez\' div\'*' words_Dispel_evil = /substitute -p %* @{Cyellow}[Dispel evil]@{n}
/def -i -F -q -t'*\'whoosy banzziii pal eeeiizz dooneb\'*' words_Dispel_good = /substitute -p %* @{Cyellow}[Dispel good]@{n}
/def -i -F -q -t'*\'removezzzzzarmour\'*' words_Dispel_magical_protection = /substitute -p %* @{Cyellow}[Dispel magical protection]@{n}
/def -i -F -q -t'*\'Sanctum disqum\'*' words_Dispel_undead = /substitute -p %* @{Cyellow}[Dispel undead]@{n}
/def -i -F -q -t'*\'diiiiuuunz aaanziz\'*' words_Displacement = /substitute -p %* @{Cyellow}[Displacement]@{n}
/def -i -F -q -t'*\'fzz zur fehh\'*' words_Disruption = /substitute -p %* @{Cyellow}[Disruption]@{n} (acid1)
/def -i -F -q -t'*\'In the name of Faerwon, make this shield stronger\'*' words_Divine_enhancement = /substitute -p %* @{Cyellow}[Divine enhancement]@{n}
/def -i -F -q -t'*\'mun enoni oli rakoni\'*' words_Dragonify = /substitute -p %* @{Cyellow}[Dragonify]@{n}
/def -i -F -q -t'*\'enfuego delmigo\'*' words_Drain_ally = /substitute -p %* @{Cyellow}[Drain ally]@{n}
/def -i -F -q -t'*\'enfuego delvivendo\'*' words_Drain_enemy = /substitute -p %* @{Cyellow}[Drain enemy]@{n}
/def -i -F -q -t'*\'enfuego delcosa\'*' words_Drain_item = /substitute -p %* @{Cyellow}[Drain item]@{n}
/def -i -F -q -t'*\'\$ \!\^\'*' words_Drain_pool = /substitute -p %* @{Cyellow}[Drain pool]@{n}
/def -i -F -q -t'*\'enfuegome delterra\'*' words_Drain_room = /substitute -p %* @{Cyellow}[Drain room]@{n}
/def -i -F -q -t'*\'hooooooooooowwwwwwwwwwwlllllllllllllll\'*' words_Drying_wind = /substitute -p %* @{Cyellow}[Drying wind]@{n}
/def -i -F -q -t'*\'\!\( \*\)\'*' words_Earth_blood = /substitute -p %* @{Cyellow}[Earth blood]@{n}
/def -i -F -q -t'*\'\% \!\^\'*' words_Earth_power = /substitute -p %* @{Cyellow}[Earth power]@{n}
/def -i -F -q -t'*\'\% \!\(\'*' words_Earth_skin = /substitute -p %* @{Cyellow}[Earth skin]@{n}
/def -i -F -q -t'*\'\%\'*' words_Earthquake = /substitute -p %* @{Cyellow}[Earthquake]@{n}
/def -i -F -q -t'*\'Ziiiiiiiiiiit Ziit Ziiiit\'*' words_Electric_field = /substitute -p %* @{Cyellow}[Electric field]@{n}
/def -i -F -q -t'*\'zot mar nak grttzt\'*' words_Electrocution = /substitute -p %* @{Cyellow}[Electrocution]@{n} (elec5)
/def -i -F -q -t'*\'hhhnnnnnrrrrraaahhh\!\!\'*' words_Energy_aura = /substitute -p %* @{Cyellow}[Energy aura]@{n}
/def -i -F -q -t'*\'kablaaaammmmm bliitz zundfer\'*' words_Energy_channeling = /substitute -p %* @{Cyellow}[Energy channeling]@{n} (elec-P1)
/def -i -F -q -t'*\'yugfzhrrr suuck suuuuuck suuuuuuuuuuck\'*' words_Energy_drain = /substitute -p %* @{Cyellow}[Energy drain]@{n}
/def -i -F -q -t'*\'incantar enfeugo aggriva\'*' words_Energy_vortex = /substitute -p %* @{Cyellow}[Energy vortex]@{n}
/def -i -F -q -t'*\'vaka vanha vainamoinen\'*' words_Entropy = /substitute -p %* @{Cyellow}[Entropy]@{n}
/def -i -F -q -t'*\'siwwis duumof\'*' words_Enwize = /substitute -p %* @{Cyellow}[Enwize]@{n}
/def -i -F -q -t'*\'Aryu Xperienced\'*' words_Essence_shield = /substitute -p %* @{Cyellow}[Essence shield]@{n}
/def -i -F -q -t'*\'qor monoliftus\'*' words_Ether_boundary = /substitute -p %* @{Cyellow}[Ether boundary]@{n} (asphyx-P1)
/def -i -F -q -t'*\'transformaticus minimus\'*' words_Feather_weight = /substitute -p %* @{Cyellow}[Feather weight]@{n}
/def -i -F -q -t'*\'nitin uurthg\'*' words_Feeblemind = /substitute -p %* @{Cyellow}[Feeblemind]@{n}
/def -i -F -q -t'*\'wheeeaaaaaa oooooo\'*' words_Field_of_fear = /substitute -p %* @{Cyellow}[Field of fear]@{n}
/def -i -F -q -t'*\'ja nyt kenka kepposasti nousee\'*' words_Field_of_light = /substitute -p %* @{Cyellow}[Field of light]@{n}
/def -i -F -q -t'*\'fah zur semen\'*' words_Fire_blast = /substitute -p %* @{Cyellow}[Fire blast]@{n} (fire3)
/def -i -F -q -t'*\'zing yulygul bugh\'*' words_Fireball = /substitute -p %* @{Cyellow}[Fireball]@{n}
/def -i -F -q -t'*\'fah zur sanc\'*' words_Firebolt = /substitute -p %* @{Cyellow}[Firebolt]@{n} (fire2)
/def -i -F -q -t'*\'fah zur fehh\'*' words_Flame_arrow = /substitute -p %* @{Cyellow}[Flame arrow]@{n} (fire1)
/def -i -F -q -t'*\'Polo Polomii\'*' words_Flame_fists = /substitute -p %* @{Cyellow}[Flame fists]@{n}
/def -i -F -q -t'*\'huppa huppa tiki tiki\'*' words_Flame_shield = /substitute -p %* @{Cyellow}[Flame shield]@{n} (fire-P2)
/def -i -F -q -t'*\'ex\'domus naz\'*' words_Flames_of_righteousness = /substitute -p %* @{Cyellow}[Flames of righteousness]@{n}
/def -i -F -q -t'*\'cah zur sanc\'*' words_Flaming_ice = /substitute -p %* @{Cyellow}[Flaming ice]@{n} (cold2)
/def -i -F -q -t'*\'\^ \!\)\'*' words_Flex_shield = /substitute -p %* @{Cyellow}[Flex shield]@{n}
/def -i -F -q -t'*\'jammpa humppa ryydy mopsi\'*' words_Flip = /substitute -p %* @{Cyellow}[Flip]@{n}
/def -i -F -q -t'*\'rise Rise RISE\'*' words_Floating = /substitute -p %* @{Cyellow}[Floating]@{n}
/def -i -F -q -t'*\'rex car bus xzar\'*' words_Floating_disc = /substitute -p %* @{Cyellow}[Floating disc]@{n}
/def -i -F -q -t'*\'lentavia lauseita\'*' words_Floating_letters = /substitute -p %* @{Cyellow}[Floating letters]@{n}
/def -i -F -q -t'*\'ztonez des deckers\'*' words_Force_absorption = /substitute -p %* @{Cyellow}[Force absorption]@{n}
/def -i -F -q -t'*\'xulu tango charlie\'*' words_Force_dome = /substitute -p %* @{Cyellow}[Force dome]@{n}
/def -i -F -q -t'*\'thoiiiiiisss huuuiahashn\'*' words_Force_shield = /substitute -p %* @{Cyellow}[Force shield]@{n}
/def -i -F -q -t'*\'sulta taiat pois, mulle hyva mieli taikadaikaduu\'*' words_Forget = /substitute -p %* @{Cyellow}[Forget]@{n}
/def -i -F -q -t'*\'zot mar nak semen\'*' words_Forked_lightning = /substitute -p %* @{Cyellow}[Forked lightning]@{n} (elec4)
/def -i -F -q -t'*\'skaki barictos yetz fiil\'*' words_Frost_insulation = /substitute -p %* @{Cyellow}[Frost insulation]@{n} (cold-P1)
/def -i -F -q -t'*\'nbarrimon zfettix roi\'*' words_Frost_shield = /substitute -p %* @{Cyellow}[Frost shield]@{n} (cold-P2)
/def -i -F -q -t'*\'\& \^\'*' words_Gem_fire = /substitute -p %* @{Cyellow}[Gem fire]@{n}
/def -i -F -q -t'*\'rtsstr mof\'*' words_Giant_strength = /substitute -p %* @{Cyellow}[Giant strength]@{n}
/def -i -F -q -t'*\'Grant me the power, the fire from within\'*' words_Glory_of_destruction = /substitute -p %* @{Cyellow}[Glory of destruction]@{n}
/def -i -F -q -t'*\'grrreee gelowwa\'*' words_Glow = /substitute -p %* @{Cyellow}[Glow]@{n}
/def -i -F -q -t'*\'flzeeeziiiiying nyyyaaa\'*' words_Go = /substitute -p %* @{Cyellow}[Go]@{n}
/def -i -F -q -t'*\'gtzt mar nak grttzt\'*' words_Golden_arrow = /substitute -p %* @{Cyellow}[Golden arrow]@{n} (magic5)
/def -i -F -q -t'*\'shalambala shoashu\'*' words_Golem_heal = /substitute -p %* @{Cyellow}[Golem heal]@{n}
/def -i -F -q -t'*\'sezdaron montir\'*' words_Good_berry = /substitute -p %* @{Cyellow}[Good berry]@{n}
/def -i -F -q -t'*\'noccon duumof\'*' words_Granitize = /substitute -p %* @{Cyellow}[Granitize]@{n}
/def -i -F -q -t'*\'vas na ful\'*' words_Greater_darkness = /substitute -p %* @{Cyellow}[Greater darkness]@{n}
/def -i -F -q -t'*\'vas ful\'*' words_Greater_light = /substitute -p %* @{Cyellow}[Greater light]@{n}
/def -i -F -q -t'*\'Judicandee iocus merciaa Tarmalen\'*' words_Guardian_angel = /substitute -p %* @{Cyellow}[Guardian angel]@{n}
/def -i -F -q -t'*\'cah mar nak grttzt gnatlnamauch\'*' words_Hailstorm = /substitute -p %* @{Cyellow}[Hailstorm]@{n} (cold-A2)
/def -i -F -q -t'*\'ruotsalainen ensiapu\'*' words_Half_harm = /substitute -p %* @{Cyellow}[Half harm]@{n}
/def -i -F -q -t'*\'pzzzar paf\'*' words_Half_heal = /substitute -p %* @{Cyellow}[Half heal]@{n}
/def -i -F -q -t'*\'huumeet miehen tiella pitaa\'*' words_Hallucination = /substitute -p %* @{Cyellow}[Hallucination]@{n}
/def -i -F -q -t'*\'puujalka jumalauta\'*' words_Harm = /substitute -p %* @{Cyellow}[Harm]@{n}
/def -i -F -q -t'*\'PAF PAF PAF\!\'*' words_Harm_body = /substitute -p %* @{Cyellow}[Harm body]@{n}
/def -i -F -q -t'*\'sakenoivasta voimasta\'*' words_Haste = /substitute -p %* @{Cyellow}[Haste]@{n}
/def -i -F -q -t'*\'pzzarr\'*' words_Heal = /substitute -p %* @{Cyellow}[Heal]@{n}
/def -i -F -q -t'*\'koko mudi kuntoon, hep\'*' words_Heal_all = /substitute -p %* @{Cyellow}[Heal all]@{n}
/def -i -F -q -t'*\'ZAP ZAP ZAP\!\'*' words_Heal_body = /substitute -p %* @{Cyellow}[Heal body]@{n}
/def -i -F -q -t'*\'judicandus littleee\'*' words_Heal_self = /substitute -p %* @{Cyellow}[Heal self]@{n}
/def -i -F -q -t'*\'hot hot not zeis daimons\'*' words_Heat_reduction = /substitute -p %* @{Cyellow}[Heat reduction]@{n} (fire-P1)
/def -i -F -q -t'*\'sanctus \. o O\'*' words_Heavenly_protection = /substitute -p %* @{Cyellow}[Heavenly protection]@{n}
/def -i -F -q -t'*\'tonnikalaa\'*' words_Heavy_weight = /substitute -p %* @{Cyellow}[Heavy weight]@{n}
/def -i -F -q -t'*\'yugzhrr\'*' words_Hemorrhage = /substitute -p %* @{Cyellow}[Hemorrhage]@{n}
/def -i -F -q -t'*\'\& \^\'*' words_Hoar_frost = /substitute -p %* @{Cyellow}[Hoar frost]@{n}
/def -i -F -q -t'*\'Sanctum circum\'*' words_Holy_bolt = /substitute -p %* @{Cyellow}[Holy bolt]@{n}
/def -i -F -q -t'*\'ddracc\'*' words_Holy_cross = /substitute -p %* @{Cyellow}[Holy cross]@{n}
/def -i -F -q -t'*\'Sanctus inxze\'*' words_Holy_hand = /substitute -p %* @{Cyellow}[Holy hand]@{n}
/def -i -F -q -t'*\'Avee Alee adudaaa\.\.\'*' words_Holy_way = /substitute -p %* @{Cyellow}[Holy way]@{n}
/def -i -F -q -t'*\'liz\'*' words_Holy_wind = /substitute -p %* @{Cyellow}[Holy wind]@{n}
/def -i -F -q -t'*\'Khizanth Arachnidus Vitalis\'*' words_Hunger_of_the_spider = /substitute -p %* @{Cyellow}[Hunger of the spider]@{n}
/def -i -F -q -t'*\'cah mar nak semen\'*' words_Icebolt = /substitute -p %* @{Cyellow}[Icebolt]@{n} (cold4)
/def -i -F -q -t'*\'mega visa huijari\'*' words_Identify = /substitute -p %* @{Cyellow}[Identify]@{n}
/def -i -F -q -t'*\'srR\' Upon\^nep\'*' words_Identify_relic = /substitute -p %* @{Cyellow}[Identify relic]@{n}
/def -i -F -q -t'*\'fah relep krlnpth\'*' words_Immolate = /substitute -p %* @{Cyellow}[Immolate]@{n}
/def -i -F -q -t'*\'imprickening zang gah\'*' words_Imprisonment = /substitute -p %* @{Cyellow}[Imprisonment]@{n}
/def -i -F -q -t'*\'demoni on pomoni\'*' words_Infravision = /substitute -p %* @{Cyellow}[Infravision]@{n}
/def -i -F -q -t'*\'nitin duumof\'*' words_Intelligize = /substitute -p %* @{Cyellow}[Intelligize]@{n}
/def -i -F -q -t'*\'\!\?\'*' words_Inquiry_to_ahm = /substitute -p %* @{Cyellow}[Inquiry to ahm]@{n}
/def -i -F -q -t'*\'\.\.\.\.\. \.\.\.\. \.\.\. \.\. \. \.\!\'*' words_Invisibility = /substitute -p %* @{Cyellow}[Invisibility]@{n}
/def -i -F -q -t'*\'nostaaaanndiz noszum\'*' words_Iron_will = /substitute -p %* @{Cyellow}[Iron will]@{n}
/def -i -F -q -t'*\'h\'njya\'*' words_Item_dispersion_shield = /substitute -p %* @{Cyellow}[Item dispersion shield]@{n}
/def -i -F -q -t'*\'Green skins, white skins, black skins, purple skins\. Big minds, small minds, dumb minds, silly minds\. Can you see through yourself, I care not, for I can\. I can see what you wear and what you bear, disguised or not, you\'re a book for me to read\.\'*' words_Jesters_trivia = /substitute -p %* @{Cyellow}[Jesters trivia]@{n}
/def -i -F -q -t'*\'krkx mar nak grttzt gnatlnamauch\'*' words_Killing_cloud = /substitute -p %* @{Cyellow}[Killing cloud]@{n} (pois-A2)
/def -i -F -q -t'*\'If you look behind a spider web, when it is covered with frost, You may see a tiny pixie, who perhaps is a little bit lost\. That tiny pixie is full of spirit representing goodness and light, The embodiment of joy and laughter, of passion and sheer delight\. In a world of pure imagination, and a mind full of magical dreams, An enchanted forest can exist, and so can a pixie it seems\.\'*' words_Kings_feast = /substitute -p %* @{Cyellow}[Kings feast]@{n}
/def -i -F -q -t'*\'nyyjoo happa hilleiksis\'*' words_Knowledge_drain = /substitute -p %* @{Cyellow}[Knowledge drain]@{n}
/def -i -F -q -t'*\'Ab sinestris, mortum demitteri\'*' words_Last_rites = /substitute -p %* @{Cyellow}[Last rites]@{n}
/def -i -F -q -t'*\'fah mar nak grttzt\'*' words_Lava_blast = /substitute -p %* @{Cyellow}[Lava blast]@{n} (fire5)
/def -i -F -q -t'*\'fah mar nak grttzt gnatlnamauch\'*' words_Lava_storm = /substitute -p %* @{Cyellow}[Lava storm]@{n} (fire-A2)
/def -i -F -q -t'*\'Renew our strength\'*' words_Laying_on_hands = /substitute -p %* @{Cyellow}[Laying on hands]@{n}
/def -i -F -q -t'*\'Impuqueto es Bien\'*' words_Lessen_poison = /substitute -p %* @{Cyellow}[Lessen poison]@{n}
/def -i -F -q -t'*\'gtzt zur semen\'*' words_Levin_bolt = /substitute -p %* @{Cyellow}[Levin bolt]@{n} (magic3)
/def -i -F -q -t'*\'etati elem ekam\'*' words_Levitation = /substitute -p %* @{Cyellow}[Levitation]@{n}
/def -i -F -q -t'*\'gimme urhits\'*' words_Life_leech = /substitute -p %* @{Cyellow}[Life leech]@{n}
/def -i -F -q -t'*\'Corporem Connecticut Corporee\'*' words_Life_link = /substitute -p %* @{Cyellow}[Life link]@{n}
/def -i -F -q -t'*\'ful\'*' words_Light = /substitute -p %* @{Cyellow}[Light]@{n}
/def -i -F -q -t'*\'zot zur sanc\'*' words_Lightning_bolt = /substitute -p %* @{Cyellow}[Lightning bolt]@{n} (elec2)
/def -i -F -q -t'*\'ohm\'*' words_Lightning_shield = /substitute -p %* @{Cyellow}[Lightning shield]@{n} (elec-P2)
/def -i -F -q -t'*\'zot mar nak grttzt gnatlnamauch\'*' words_Lightning_storm = /substitute -p %* @{Cyellow}[Lightning storm]@{n} (elec-A2)
/def -i -F -q -t'*\'meke tul magic\'*' words_Magic_dispersion = /substitute -p %* @{Cyellow}[Magic dispersion]@{n} (magic-P1)
/def -i -F -q -t'*\'gtzt mar nak grttzt gnatlnamauch\'*' words_Magic_eruption = /substitute -p %* @{Cyellow}[Magic eruption]@{n} (magic-A2)
/def -i -F -q -t'*\'gtzt zur fehh\'*' words_Magic_missile = /substitute -p %* @{Cyellow}[Magic missile]@{n} (magic1)
/def -i -F -q -t'*\'gtzt zur semen gnatlnamauch\'*' words_Magic_wave = /substitute -p %* @{Cyellow}[Magic wave]@{n} (magic-A1)
/def -i -F -q -t'*\'judicandus pafzarmus\'*' words_Major_heal = /substitute -p %* @{Cyellow}[Major heal]@{n}
/def -i -F -q -t'*\'judicandus puorgo mangenic\'*' words_Major_party_heal = /substitute -p %* @{Cyellow}[Major party heal]@{n}
/def -i -F -q -t'*\'viiltaja jaska\'*' words_Make_scar = /substitute -p %* @{Cyellow}[Make scar]@{n}
/def -i -F -q -t'*\'I HATE MAGIC\'*' words_Mana_drain = /substitute -p %* @{Cyellow}[Mana drain]@{n}
/def -i -F -q -t'*\'nullum driiiks umbah mana\'*' words_Mana_shield = /substitute -p %* @{Cyellow}[Mana shield]@{n}
/def -i -F -q -t'*\'Zmasching Pupkins\'s infanitsadnnes\'*' words_Mellon_collie = /substitute -p %* @{Cyellow}[Mellon collie]@{n}
/def -i -F -q -t'*\'Once there were two knights and maidens They\'d walk together Out in the gardens In all kinds of weather The maidens had other plans for the two knights They\'d give them potions And make them see dreams and lights\'*' words_Melodical_embracement = /substitute -p %* @{Cyellow}[Melodical embracement]@{n}
/def -i -F -q -t'*\'Young bard he saw, a misjustice done, he took his instrument and pointed as a gun\'*' words_Melody_of_the_misadventurer = /substitute -p %* @{Cyellow}[Melody of the misadventurer]@{n}
/def -i -F -q -t'*\'vaxtextraktdryck\'*' words_Mental_glance = /substitute -p %* @{Cyellow}[Mental glance]@{n}
/def -i -F -q -t'*\'kakakaaa tsooon\'*' words_Mental_watch = /substitute -p %* @{Cyellow}[Mental watch]@{n}
/def -i -F -q -t'*\'fah mar nak semen\'*' words_Meteor_blast = /substitute -p %* @{Cyellow}[Meteor blast]@{n} (fire4)
/def -i -F -q -t'*\'fah zur sanc gnatlnamauch\'*' words_Meteor_swarm = /substitute -p %* @{Cyellow}[Meteor swarm]@{n} (fire-A1)
/def -i -F -q -t'*\'omm zur fehh\'*' words_Mind_blast = /substitute -p %* @{Cyellow}[Mind blast]@{n}
/def -i -F -q -t'*\'Annatheer graaweizta\'*' words_Mind_development = /substitute -p %* @{Cyellow}[Mind development]@{n}
/def -i -F -q -t'*\'omm mar nak semen\'*' words_Mind_disruption = /substitute -p %* @{Cyellow}[Mind disruption]@{n}
/def -i -F -q -t'*\'memono locati\'*' words_Mind_store = /substitute -p %* @{Cyellow}[Mind store]@{n}
/def -i -F -q -t'*\'diir mieelis sxil miarr mieelin\'*' words_Mindseize = /substitute -p %* @{Cyellow}[Mindseize]@{n}
/def -i -F -q -t'*\'judicandus pzarcumus\'*' words_Minor_heal = /substitute -p %* @{Cyellow}[Minor heal]@{n}
/def -i -F -q -t'*\'judicandus puorgo ignius\'*' words_Minor_party_heal = /substitute -p %* @{Cyellow}[Minor party heal]@{n}
/def -i -F -q -t'*\'peilikuvia ja lasinsirpaleita\'*' words_Mirror_image = /substitute -p %* @{Cyellow}[Mirror image]@{n}
/def -i -F -q -t'*\'buuuummbzdiiiiiibummm\'*' words_Mobile_cannon = /substitute -p %* @{Cyellow}[Mobile cannon]@{n}
/def -i -F -q -t'*\'\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\'*' words_Money_is_power = /substitute -p %* @{Cyellow}[Money is power]@{n}
/def -i -F -q -t'*\'daaa timaaa of daaa maaanth\'*' words_Moon_sense = /substitute -p %* @{Cyellow}[Moon sense]@{n}
/def -i -F -q -t'*\'fingerrrr ovuuulah\'*' words_Mould_ring = /substitute -p %* @{Cyellow}[Mould ring]@{n}
/def -i -F -q -t'*\'Donations welcome\'*' words_Musicians_alm = /substitute -p %* @{Cyellow}[Musicians alm]@{n}
/def -i -F -q -t'*\'Naturallis Judicandus Imellys\'*' words_Natural_renewal = /substitute -p %* @{Cyellow}[Natural renewal]@{n}
/def -i -F -q -t'*\'null, nill, noll, nutin\'*' words_Neutralize_field = /substitute -p %* @{Cyellow}[Neutralize field]@{n}
/def -i -F -q -t'*\'Thar\! Rauko\! Mor\! Ris-Rim\! Fuin-Heru\! GOR\! Gurthgwath\!n\'*' words_Noituloves_deathlore = /substitute -p %* @{Cyellow}[Noituloves deathlore]@{n}
/def -i -F -q -t'*\'dIsCHoRD\'*' words_Noituloves_dischord = /substitute -p %* @{Cyellow}[Noituloves dischord]@{n}
/def -i -F -q -t'*\'vorek ky taree\'*' words_Paralyze = /substitute -p %* @{Cyellow}[Paralyze]@{n}
/def -i -F -q -t'*\'etsi poika pippuria\'*' words_Party_banish = /substitute -p %* @{Cyellow}[Party banish]@{n}
/def -i -F -q -t'*\'jimmiii fixiiii\'*' words_Patch_item = /substitute -p %* @{Cyellow}[Patch item]@{n}
/def -i -F -q -t'*\'Fo fu fe fum, Lord of the Winds, I know Thy ways, I know Thy names, I know Thy rest\. Fo fu fe fum, show me paths or slay me now\. Fo fe fi fum\.\'*' words_Pathfinder = /substitute -p %* @{Cyellow}[Pathfinder]@{n}
/def -i -F -q -t'*\'riljya\'*' words_Personal_force_field = /substitute -p %* @{Cyellow}[Personal force field]@{n}
/def -i -F -q -t'*\'Harken to me and hear my plea, disease is what I call to thee\'*' words_Pestilence = /substitute -p %* @{Cyellow}[Pestilence]@{n}
/def -i -F -q -t'*\'xafe uurthq\'*' words_Phaze_shift = /substitute -p %* @{Cyellow}[Phaze shift]@{n}
/def -i -F -q -t'*\'saugaiii\'*' words_Poison = /substitute -p %* @{Cyellow}[Poison]@{n}
/def -i -F -q -t'*\'krkx zur sanc\'*' words_Poison_blast = /substitute -p %* @{Cyellow}[Poison blast]@{n} (pois2)
/def -i -F -q -t'*\'ddt ddt ddt is good for you and me\!\'*' words_Poison_cloud = /substitute -p %* @{Cyellow}[Poison cloud]@{n}
/def -i -F -q -t'*\'krkx zur semen gnatlnamauch\'*' words_Poison_spray = /substitute -p %* @{Cyellow}[Poison spray]@{n} (pois-A1)
/def -i -F -q -t'*\'krkx mar nak semen\'*' words_Power_blast = /substitute -p %* @{Cyellow}[Power blast]@{n} (pois4)
/def -i -F -q -t'*\'Khizanth Arachnidus Satisfusmus\'*' words_Prayer_to_the_spider_queen = /substitute -p %* @{Cyellow}[Prayer to the spider queen]@{n}
/def -i -F -q -t'*\'phylli phylli\'*' words_Prepare_flask = /substitute -p %* @{Cyellow}[Prepare flask]@{n}
/def -i -F -q -t'*\'upo huurre helkama\'*' words_Preserve_corpse = /substitute -p %* @{Cyellow}[Preserve corpse]@{n}
/def -i -F -q -t'*\'blueeeeeeeeeee\*\*\*\*saka\?\?am\!a\'*' words_Protect_armour = /substitute -p %* @{Cyellow}[Protect armour]@{n}
/def -i -F -q -t'*\'blueeeeeeeeeee\*\*\*\*saka\?\?am\!a\'*' words_Protect_item = /substitute -p %* @{Cyellow}[Protect item]@{n}
/def -i -F -q -t'*\'blueeeeeeeeeee\*\*\*\*saka\?\?am\!a\'*' words_Protect_weapon = /substitute -p %* @{Cyellow}[Protect weapon]@{n}
/def -i -F -q -t'*\'sanctus Exzordus\'*' words_Protection_from_evil = /substitute -p %* @{Cyellow}[Protection from evil]@{n}
/def -i -F -q -t'*\'Good is dumb\'*' words_Protection_from_good = /substitute -p %* @{Cyellow}[Protection from good]@{n}
/def -i -F -q -t'*\'omm zur semen\'*' words_Psi_blast = /substitute -p %* @{Cyellow}[Psi blast]@{n}
/def -i -F -q -t'*\'omm zur sanc\'*' words_Psibolt = /substitute -p %* @{Cyellow}[Psibolt]@{n}
/def -i -F -q -t'*\'all for one, gather around me\'*' words_Psionic_phalanx = /substitute -p %* @{Cyellow}[Psionic phalanx]@{n}
/def -i -F -q -t'*\'niihek atierapip aj niiramaan aaffaj\'*' words_Psionic_shield = /substitute -p %* @{Cyellow}[Psionic shield]@{n}
/def -i -F -q -t'*\'tora tora tora\'*' words_Psychic_crush = /substitute -p %* @{Cyellow}[Psychic crush]@{n}
/def -i -F -q -t'*\'aamad ato naav aanarub atyak ala\'*' words_Psychic_purge = /substitute -p %* @{Cyellow}[Psychic purge]@{n}
/def -i -F -q -t'*\'toughen da mind reeez un biis\'*' words_Psychic_sanctuary = /substitute -p %* @{Cyellow}[Psychic sanctuary]@{n}
/def -i -F -q -t'*\'omm zur semen gnatlnamauch\'*' words_Psychic_shout = /substitute -p %* @{Cyellow}[Psychic shout]@{n}
/def -i -F -q -t'*\'omm mar nak grttzt gnatlnamauch\'*' words_Psychic_storm = /substitute -p %* @{Cyellow}[Psychic storm]@{n}
/def -i -F -q -t'*\'iiiihihihih hihihihih hihihih iiiiiiiihihihih\'*' words_Punishment = /substitute -p %* @{Cyellow}[Punishment]@{n}
/def -i -F -q -t'*\'jumpiiz laika wabbitzz\'*' words_Quicksilver = /substitute -p %* @{Cyellow}[Quicksilver]@{n}
/def -i -F -q -t'*\'huku mopo huku\'*' words_Rain = /substitute -p %* @{Cyellow}[Rain]@{n}
/def -i -F -q -t'*\'vokinsalak elfirtluassa\'*' words_Raise_dead = /substitute -p %* @{Cyellow}[Raise dead]@{n}
/def -i -F -q -t'*\'Blaarh ARGHAGHAHAHA URAAAH BELARGH\!\'*' words_Reanimation = /substitute -p %* @{Cyellow}[Reanimation]@{n}
/def -i -F -q -t'*\'Grant this the caustic touch, to clense the world\'*' words_Reaping_of_bile = /substitute -p %* @{Cyellow}[Reaping of bile]@{n}
/def -i -F -q -t'*\'sakat ikkiak satsjaieh\'*' words_Reflector_shield = /substitute -p %* @{Cyellow}[Reflector shield]@{n}
/def -i -F -q -t'*\'nilaehz temnahecne\'*' words_Regeneration = /substitute -p %* @{Cyellow}[Regeneration]@{n}
/def -i -F -q -t'*\'henget uusix\'*' words_Reincarnation = /substitute -p %* @{Cyellow}[Reincarnation]@{n}
/def -i -F -q -t'*\'hypin pompin luokses juoksen\'*' words_Relocate = /substitute -p %* @{Cyellow}[Relocate]@{n}
/def -i -F -q -t'*\'bat-o-mat\'*' words_Remote_banking = /substitute -p %* @{Cyellow}[Remote banking]@{n}
/def -i -F -q -t'*\'judicandus saugaiii\'*' words_Remove_poison = /substitute -p %* @{Cyellow}[Remove poison]@{n}
/def -i -F -q -t'*\'lkzaz zueei enz orn\'*' words_Remove_scar = /substitute -p %* @{Cyellow}[Remove scar]@{n}
/def -i -F -q -t'*\'enfuego delyo\'*' words_Replenish_ally = /substitute -p %* @{Cyellow}[Replenish ally]@{n}
/def -i -F -q -t'*\'shamarubu incixtes delfo\'*' words_Repulsor_aura = /substitute -p %* @{Cyellow}[Repulsor aura]@{n} (magic-P2)
/def -i -F -q -t'*\'bii thee dzname uv tii blaaaz drazon\'*' words_Resist_disintegrate = /substitute -p %* @{Cyellow}[Resist disintegrate]@{n}
/def -i -F -q -t'*\'zicks laai qluu\'*' words_Resist_dispel = /substitute -p %* @{Cyellow}[Resist dispel]@{n}
/def -i -F -q -t'*\'Ourglazz Schmourglazz\'*' words_Resist_entropy = /substitute -p %* @{Cyellow}[Resist entropy]@{n}
/def -i -F -q -t'*\'Break like the wind\'*' words_Resist_gaseous_form = /substitute -p %* @{Cyellow}[Resist gaseous form]@{n}
/def -i -F -q -t'*\'Siwa on selvaa saastoa\.\'*' words_Restore = /substitute -p %* @{Cyellow}[Restore]@{n}
/def -i -F -q -t'*\'tuo fo wen stanhc\'*' words_Resurrect = /substitute -p %* @{Cyellow}[Resurrect]@{n}
/def -i -F -q -t'*\'\!\* \*\'*' words_Runic_heal = /substitute -p %* @{Cyellow}[Runic heal]@{n}
/def -i -F -q -t'*\'Exzorde\' Å\'*' words_Saintly_touch = /substitute -p %* @{Cyellow}[Saintly touch]@{n}
/def -i -F -q -t'*\'Creo Herbamus Satisfus\'*' words_Satiate_person = /substitute -p %* @{Cyellow}[Satiate person]@{n}
/def -i -F -q -t'*\'\$\%\&\@ \#\*\%\@\*\@\# \$\&\*\@\#\'*' words_See_invisible = /substitute -p %* @{Cyellow}[See invisible]@{n}
/def -i -F -q -t'*\'ahne paskianen olen ma kun taikuutta nahda tahdon\'*' words_See_magic = /substitute -p %* @{Cyellow}[See magic]@{n}
/def -i -F -q -t'*\'ogyawaelbirroh\'*' words_See_the_light = /substitute -p %* @{Cyellow}[See the light]@{n}
/def -i -F -q -t'*\'likz az zurgeeon\'*' words_Sex_change = /substitute -p %* @{Cyellow}[Sex change]@{n}
/def -i -F -q -t'*\'ful na \.\. \.q\^st\'*' words_Shadow_armour = /substitute -p %* @{Cyellow}[Shadow armour]@{n}
/def -i -F -q -t'*\'Haii\!\'*' words_Shadow_leap = /substitute -p %* @{Cyellow}[Shadow leap]@{n}
/def -i -F -q -t'*\'\!\(\'*' words_Shapechange = /substitute -p %* @{Cyellow}[Shapechange]@{n}
/def -i -F -q -t'*\'That I have set free, return to me\'*' words_Shattered_feast = /substitute -p %* @{Cyellow}[Shattered feast]@{n}
/def -i -F -q -t'*\'withing thang walz\'*' words_Shelter = /substitute -p %* @{Cyellow}[Shelter]@{n}
/def -i -F -q -t'*\'nyiaha llaimay exchekes ployp\'*' words_Shield_of_detoxification = /substitute -p %* @{Cyellow}[Shield of detoxification]@{n} (poison-P2)
/def -i -F -q -t'*\'Grant your worshipper your protection\'*' words_Shield_of_faith = /substitute -p %* @{Cyellow}[Shield of faith]@{n}
/def -i -F -q -t'*\'nsiiznau\'*' words_Shield_of_protection = /substitute -p %* @{Cyellow}[Shield of protection]@{n}
/def -i -F -q -t'*\'kallora kassam\'*' words_Shift_blade = /substitute -p %* @{Cyellow}[Shift blade]@{n}
/def -i -F -q -t'*\'zot zur fehh\'*' words_Shocking_grasp = /substitute -p %* @{Cyellow}[Shocking grasp]@{n} (elec1)
/def -i -F -q -t'*\'aaaaaaaaattchhhoooooooooo\'*' words_Sneezing_powder = /substitute -p %* @{Cyellow}[Sneezing powder]@{n}
/def -i -F -q -t'*\'Now that two decades gone by and I know that\'s a long time, para tiempo means nada nunca\. Cause I\'m still the same asshole and I still wet my pants everytime that I see your face\! \(who are you\?\) Introduce yourself\! \(right on\!\)\'*' words_Soothing_sounds = /substitute -p %* @{Cyellow}[Soothing sounds]@{n}
/def -i -F -q -t'*\'naxanhar hecnatemne\'*' words_Soul_hold = /substitute -p %* @{Cyellow}[Soul hold]@{n}
/def -i -F -q -t'*\'sanctus angeliq\'*' words_Soul_shield = /substitute -p %* @{Cyellow}[Soul shield]@{n}
/def -i -F -q -t'*\'Hear this charm, there in the dark, lurking fiends, devouring sharks\. Lend me your ears, out in the mist\. Where secrets lie, you cannot resist\. The paths I traveled, the abyss I found, shall not be seen by any hound\. Accept that, when these rhymes will end, only silence is your friend\'*' words_Sounds_of_silence = /substitute -p %* @{Cyellow}[Sounds of silence]@{n}
/def -i -F -q -t'*\'xeddex duumof\'*' words_Speed = /substitute -p %* @{Cyellow}[Speed]@{n}
/def -i -F -q -t'*\'moon fiksu, soot tyhma - opi tasta taika\'*' words_Spellteaching = /substitute -p %* @{Cyellow}[Spellteaching]@{n}
/def -i -F -q -t'*\'infernalicus thanatos arachnidos\'*' words_Spider_demon_banishment = /substitute -p %* @{Cyellow}[Spider demon banishment]@{n}
/def -i -F -q -t'*\'infernalicus nexus arachnid rex\'*' words_Spider_demon_channeling = /substitute -p %* @{Cyellow}[Spider demon channeling]@{n}
/def -i -F -q -t'*\'arachnid infernalicus arachnoidus demonicus\'*' words_Spider_demon_conjuration = /substitute -p %* @{Cyellow}[Spider demon conjuration]@{n}
/def -i -F -q -t'*\'infernalicus domus arachnid rex\'*' words_Spider_demon_control = /substitute -p %* @{Cyellow}[Spider demon control]@{n}
/def -i -F -q -t'*\'Khirsah Zokant Arachnidus\'*' words_Spider_demon_inquiry = /substitute -p %* @{Cyellow}[Spider demon inquiry]@{n}
/def -i -F -q -t'*\'infernalicus domus arachnid rex magnos\'*' words_Spider_demon_mass_sacrifice = /substitute -p %* @{Cyellow}[Spider demon mass sacrifice]@{n}
/def -i -F -q -t'*\'infernalicus intellegus arachnidos\'*' words_Spider_eye = /substitute -p %* @{Cyellow}[Spider eye]@{n}
/def -i -F -q -t'*\'Khirsah Khazanth Arachinidus\'*' words_Spider_gate = /substitute -p %* @{Cyellow}[Spider gate]@{n}
/def -i -F -q -t'*\'infernalicus claravonticus arachnidos\'*' words_Spider_gaze = /substitute -p %* @{Cyellow}[Spider gaze]@{n}
/def -i -F -q -t'*\'infernalicus conjuratis arachnidos\'*' words_Spider_servant = /substitute -p %* @{Cyellow}[Spider servant]@{n}
/def -i -F -q -t'*\'Khizanth Arachnidus Diametricus\'*' words_Spider_touch = /substitute -p %* @{Cyellow}[Spider touch]@{n}
/def -i -F -q -t'*\'Khizanth Arachnidus Walkitus\'*' words_Spider_walk = /substitute -p %* @{Cyellow}[Spider walk]@{n}
/def -i -F -q -t'*\'infernalicus thanatos arachnidos\'*' words_Spider_web = /substitute -p %* @{Cyellow}[Spider web]@{n}
/def -i -F -q -t'*\'Khizanth Arachnidus Iracundus\'*' words_Spider_wrath = /substitute -p %* @{Cyellow}[Spider wrath]@{n}
/def -i -F -q -t'*\'I\'ll swallow your soul\!\'*' words_Spirit_drain = /substitute -p %* @{Cyellow}[Spirit drain]@{n}
/def -i -F -q -t'*\'\!\( \!\!\'*' words_Star_light = /substitute -p %* @{Cyellow}[Star light]@{n}
/def -i -F -q -t'*\'ghht mar nak semen\'*' words_Strangulation = /substitute -p %* @{Cyellow}[Strangulation]@{n} (asphyx4)
/def -i -F -q -t'*\'You say you don\'t believe this unity will last, nobody said it would be perfect, but co-operate, share your pain and strength\. Together we are strong\.\'*' words_Strength_in_unity = /substitute -p %* @{Cyellow}[Strength in unity]@{n}
/def -i -F -q -t'*\'rtsstr duumof\'*' words_Strengthen = /substitute -p %* @{Cyellow}[Strengthen]@{n}
/def -i -F -q -t'*\'aflitruz\'*' words_Stoneskin = /substitute -p %* @{Cyellow}[Stoneskin]@{n}
/def -i -F -q -t'*\'ghht zur sanc\'*' words_Suffocation = /substitute -p %* @{Cyellow}[Suffocation]@{n} (asphyx2)
/def -i -F -q -t'*\'gwwaaajj\'*' words_Summon = /substitute -p %* @{Cyellow}[Summon]@{n}
/def -i -F -q -t'*\'ahieppa weaapytama nyttemmin\'*' words_Summon_blade = /substitute -p %* @{Cyellow}[Summon blade]@{n}
/def -i -F -q -t'*\'krkx mar nak grttzt\'*' words_Summon_carnal_spores = /substitute -p %* @{Cyellow}[Summon carnal spores]@{n} (pois5)
/def -i -F -q -t'*\'gtzt mar nak semen\'*' words_Summon_greater_spores = /substitute -p %* @{Cyellow}[Summon greater spores]@{n} (magic4)
/def -i -F -q -t'*\'imppy floooogah\'*' words_Summon_homonculus = /substitute -p %* @{Cyellow}[Summon homonculus]@{n}
/def -i -F -q -t'*\'gtzt zur sanc\'*' words_Summon_lesser_spores = /substitute -p %* @{Cyellow}[Summon lesser spores]@{n} (magic2)
/def -i -F -q -t'*\'hus hus hus\'*' words_Suppress_magic = /substitute -p %* @{Cyellow}[Suppress magic]@{n}
/def -i -F -q -t'*\'xafe xyyqh xckgandhuzqarr\'*' words_Teleport_with_error = /substitute -p %* @{Cyellow}[Teleport with error]@{n}
/def -i -F -q -t'*\'xafe ayz xckgandhuzqarr\'*' words_Teleport_without_error = /substitute -p %* @{Cyellow}[Teleport without error]@{n}
/def -i -F -q -t'*\'BBBBOOOOOO\!\!\!\!\'*' words_Terror = /substitute -p %* @{Cyellow}[Terror]@{n}
/def -i -F -q -t'*\'jakki makupala\'*' words_There_not_there = /substitute -p %* @{Cyellow}[There not there]@{n}
/def -i -F -q -t'*\'krkx zur fehh\'*' words_Thorn_spray = /substitute -p %* @{Cyellow}[Thorn spray]@{n} (pois1)
/def -i -F -q -t'*\'Haii\!\'*' words_Tiger_claw = /substitute -p %* @{Cyellow}[Tiger claw]@{n}
/def -i -F -q -t'*\'Tiger Power\!\'*' words_Tiger_mask = /substitute -p %* @{Cyellow}[Tiger mask]@{n}
/def -i -F -q -t'*\'morri nam pantoloosa\'*' words_Toxic_dilution = /substitute -p %* @{Cyellow}[Toxic dilution]@{n} (acid-P1)
/def -i -F -q -t'*\'\) \!\#\\\'*' words_Transfer_mana = /substitute -p %* @{Cyellow}[Transfer mana]@{n}
/def -i -F -q -t'*\'insignificus et gargantum alternos\'*' words_Transform_golem = /substitute -p %* @{Cyellow}[Transform golem]@{n}
/def -i -F -q -t'*\'nihenuak assaam no nek orrek\'*' words_Transmute_self = /substitute -p %* @{Cyellow}[Transmute self]@{n}
/def -i -F -q -t'*\'judicandus zapracus\'*' words_True_heal = /substitute -p %* @{Cyellow}[True heal]@{n}
/def -i -F -q -t'*\'judicandus eurto mangenic\'*' words_True_party_heal = /substitute -p %* @{Cyellow}[True party heal]@{n}
/def -i -F -q -t'*\'drac a duck\'*' words_Turn_undead = /substitute -p %* @{Cyellow}[Turn undead]@{n}
/def -i -F -q -t'*\'III want to ROAR, III want to SLAM, III want to bash your ass\! Hit the WALLS\! Hit the WALLS\! Go, go go I\'ll screw the BASS\! Hit the WALLS\! Hit the WALLS\!\'*' words_Uncontrollable_mosh = /substitute -p %* @{Cyellow}[Uncontrollable mosh]@{n}
/def -i -F -q -t'*\'With this ring, i do deconsecrate thee\'*' words_Unholy_matrimony = /substitute -p %* @{Cyellow}[Unholy matrimony]@{n}
/def -i -F -q -t'*\'harnaxan temnahecne\'*' words_Unpain = /substitute -p %* @{Cyellow}[Unpain]@{n}
/def -i -F -q -t'*\'ragus on etsat mumixam\!\'*' words_Unstable_mutation = /substitute -p %* @{Cyellow}[Unstable mutation]@{n}
/def -i -F -q -t'*\'Paxus\'*' words_Unstun = /substitute -p %* @{Cyellow}[Unstun]@{n}
/def -i -F -q -t'*\'ghht zur sanc gnatlnamauch\'*' words_Vacuum_ball = /substitute -p %* @{Cyellow}[Vacuum ball]@{n} (asphyx-A1)
/def -i -F -q -t'*\'ghht mar nak grttzt gnatlnamauch\'*' words_Vacuum_globe = /substitute -p %* @{Cyellow}[Vacuum globe]@{n} (asphyx-A2)
/def -i -F -q -t'*\'ghht zur fehh\'*' words_Vacuumbolt = /substitute -p %* @{Cyellow}[Vacuumbolt]@{n} (asphyx1)
/def -i -F -q -t'*\'War is TOTAL massacre, sport the war, war SUPPOORT\!\!\!\'*' words_War_ensemble = /substitute -p %* @{Cyellow}[War ensemble]@{n}
/def -i -F -q -t'*\'Jeeeeeeeeeeeesuuuuuuuus\'*' words_Water_walking = /substitute -p %* @{Cyellow}[Water walking]@{n}
/def -i -F -q -t'*\'May this become the blood of the Spider queen\'*' words_Venom_blade = /substitute -p %* @{Cyellow}[Venom blade]@{n}
/def -i -F -q -t'*\'krkx zur semen\'*' words_Venom_strike = /substitute -p %* @{Cyellow}[Venom strike]@{n} (pois3)
/def -i -F -q -t'*\'\.\.a few steps to earthen might, a few steps just go ahead me, but do I walk the right direction, is it here or there\? Just a few steps, left or right\. Spirits are what show the sight\.\'*' words_Venturers_way = /substitute -p %* @{Cyellow}[Venturers way]@{n}
/def -i -F -q -t'*\'Lost I am not but knowledge I seek for there, my friend, lies a true path for wisdom\. With a clouded mind one can not think, but small fog may enhance a presence\.\'*'  words_Vigilant_melody = /substitute -p %* @{Cyellow}[Vigilant melody]@{n}
/def -i -F -q -t'*\'spirits of nature, show me the way\!\'*' words_Wilderness_location = /substitute -p %* @{Cyellow}[Wilderness location]@{n}
/def -i -F -q -t'*\'\"\" \!\#\'*' words_Vine_mantle = /substitute -p %* @{Cyellow}[Vine mantle]@{n}
/def -i -F -q -t'*\'xeddex uurthg\'*' words_Wither = /substitute -p %* @{Cyellow}[Wither]@{n}
/def -i -F -q -t'*\'\"\# \^\'*' words_Wither_flesh = /substitute -p %* @{Cyellow}[Wither flesh]@{n}
/def -i -F -q -t'*\'mad rad dar\'*' words_Wizard_eye = /substitute -p %* @{Cyellow}[Wizard eye]@{n}
/def -i -F -q -t'*\'dymofo\'*' words_Word_of_apocalypse = /substitute -p %* @{Cyellow}[Word of apocalypse]@{n}
/def -i -F -q -t'*\'khozak\'*' words_Word_of_attrition = /substitute -p %* @{Cyellow}[Word of attrition]@{n}
/def -i -F -q -t'*\'Sherpha\!\'*' words_Word_of_destruction = /substitute -p %* @{Cyellow}[Word of destruction]@{n}
/def -i -F -q -t'*\'hraugh\'*' words_Word_of_blasting = /substitute -p %* @{Cyellow}[Word of blasting]@{n}
/def -i -F -q -t'*\'dephtua\'*' words_Word_of_genocide = /substitute -p %* @{Cyellow}[Word of genocide]@{n}
/def -i -F -q -t'*\'FRONOX\!\!\'*' words_Word_of_oblivion = /substitute -p %* @{Cyellow}[Word of oblivion]@{n}
/def -i -F -q -t'*\'vole love velo levo\'*' words_Word_of_recall = /substitute -p %* @{Cyellow}[Word of recall]@{n}
/def -i -F -q -t'*\'niinr\'*' words_Word_of_slaughter = /substitute -p %* @{Cyellow}[Word of slaughter]@{n}
/def -i -F -q -t'*\'torrfra\'*' words_Word_of_spite = /substitute -p %* @{Cyellow}[Word of spite]@{n}
/def -i -F -q -t'*\' \¤Lassum\¤ \'*' words_Wrath_of_las = /substitute -p %* @{Cyellow}[Wrath of las]@{n}
/def -i -F -q -t'*\'Akronym Htouy, Hokrune Arafax\'*' words_Youth = /substitute -p %* @{Cyellow}[Youth]@{n}
/def -i -F -q -axBCbgred,Cwhite -t'*\'sahanpurua\'*' words_Disintegrate2 = /substitute -p %* @{Cyellow}[Disintegrate]@{n}

